NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.cgpj.tfm.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.cgpj.tfm.com-cert.pem
    OrganizationalUnitIdentifier: peer
